--- 

### 2020 FALL
### DSGA1007

--- 

### HW02
### Due Date: 2020-10-08, 5PM

Firstname: Ted

Lastname: Xie

E-mail: tx607@nyu.edu


--- 

Enter your solutions below,  and submit this notebook

In [2]:
import numpy as np
import pandas as pd

### Problem 01 (10 points):

1. 1 (5 points) Write a function that iteratively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


1. 2 (5 points) Write a function that recursively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


In [3]:
#1.1
def iterative_factorial(n):
    if n < 0:
        return None
    else:
        x = 1
        for i in range(1, n + 1):
            x = x * i
        return x

print('Using the iterative_factorial function for n = 10, we get:', iterative_factorial(10),'.')

#1.2
def recursive_factorial(n):
    if n < 0:
        return None
    elif n == 0:
        return 1
    else:
        return n * recursive_factorial(n - 1)
    
print('Using the recursive_factorial function for n = 10, we get:', recursive_factorial(10),'.')

Using the iterative_factorial function for n = 10, we get: 3628800 .
Using the recursive_factorial function for n = 10, we get: 3628800 .


### Problem 02 (50 points)

Let $M$ be a real quadratic matrix, that is, the number of rows and columns are the same. 

2.1 (20 points) Write a function that *recursively* calculates the power of matrix to the exponent $k$ (by the definition of the matrix multiplication). Here $k \geq 0$ is an integer.

```def matrix_mult_rec(M, k):
    return M_to_power
```    
    

2.2 (10 points) What is the number of calls, that is, how many times the function has been called for $k=100$?

2.3 (15 points) Given the same question as one in 2.2, what is the answer for a general input $k$?

2.4. (5 points) What is the answer for `M=np.ones((5, 5))` and `k=5`?

In [5]:
#2.1
M = np.ones((5, 5))

def matrix_mult_rec(M, k):
    global calls
    calls += 1
    if M.size == 0:
        return None
    elif k == 0:
        return M ** 0
    else:
        return M *  matrix_mult_rec(M, k - 1)
#2.2
calls = 0
matrix_mult_rec(M,100)
print('The number of times the function has been called for k = 100 is',calls,'times.')
#2.3
print('The number of times the function is called for k = n is n + 1 times.')
#2.4
k = 5
print(matrix_mult_rec(M, 5))
print('The function matrix_mult_rec(M, 5) called the function 6 times.')

The number of times the function has been called for k = 100 is 101 times.
The number of times the function is called for k = n is n + 1 times.
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
The function matrix_mult_rec(M, 5) called the function 6 times.


### Problem 03 (20 points):

3.1 (5 points) Write a function that performs a bubble sort. 

3.2 (5 points) Write a function that performs a merge sort. 

3.3 (5 points) Generate a random numpy array $a$, of length $n=10000$, where each component is a random number independently and uniformly generated from the interval $[0, 1]$. 

3.4 (5 points) Estimate the run-times and print the difference when applied the functions from 3.1 and 3.2 on the array $a$. To estimate the run-times you can use the following part: 

In [10]:
#3.1
def bubble_sort(array):
    for i in range(len(array) - 1):
        for j in range(i + 1, len(array)):
            if array[i] > array[j]:
                arr[i], arr[j] = arr[j], arr[i]
                
#3.2
def merge_two(left_arr, right_arr):
    lst_result = []
    left_point, right_point = 0, 0
    while left_point < len(left_arr) and right_point < len(right_arr):
        if left_arr[left_point] <= right_arr[right_point]:
            lst_result.append(left_arr[left_point])
            left_point += 1
        else:
            lst_result.append(right_arr[right_point])
            right_point += 1
    if left_point == len(left_arr):
        lst_result += right_arr[right_point: ]
    else:
        lst_result += left_arr[left_point: ]
    return lst_result

def merge_sort(arr):
    if len(arr) <= 1:
        return arr
    middle = len(arr) // 2
    
    arr_left = arr[: middle]    
    arr_right = arr[middle: ]

    arr_left = merge_sort(arr_left)
    arr_right = merge_sort(arr_right)
    
    return list(merge_two_sorted(arr_left, arr_right))

#3.3
a = np.random.rand(1, 10000)
print(a)
#3.4

#the package datetime was not able to estimate my function because the time was so short
%timeit bubble_sort(a)

%timeit merge_sort(a)
print('Merge sort is faster than bubble sort by 143 ns per loop')

[[0.12218805 0.82600222 0.30550435 ... 0.41377906 0.87299023 0.63673372]]
262 ns ± 4.85 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
120 ns ± 0.603 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
Merge sort is faster than bubble sort by 143 ns per loop



### Problem 04 (20 points)


The provided file 'nba2020.csv' contains the schedules and information of the NBA games for 2020. Using the unix commands, covered in Lecture04, write scripts which will display:
    
4.1 (5 points) a unique list of NBA teams, provided in the file;

4.2 (5 points) the number of those NBA teams;

4.3 (5 points) a unique list of the times -- provided in the file -- when the NBA matches were played;

4.4 (5 points) the number of these unique times.

All questions are answered by using Git Bash (was not able to linux commands in Jupyter Notebook).

4.1

$ cut -d ',' -f 3 nba2020.csv | tail -n+2  | sort | uniq 

Atlanta Hawks

Boston Celtics

Brooklyn Nets

Charlotte Hornets

Chicago Bulls

Cleveland Cavaliers

Dallas Mavericks

Denver Nuggets

Detroit Pistons

Golden State Warriors

Houston Rockets

Indiana Pacers

Los Angeles Clippers

Los Angeles Lakers

Memphis Grizzlies

Miami Heat

Milwaukee Bucks

Minnesota Timberwolves

New Orleans Pelicans

New York Knicks

Oklahoma City Thunder

Orlando Magic

Philadelphia 76ers

Phoenix Suns

Portland Trail Blazers

Sacramento Kings

San Antonio Spurs

Toronto Raptors

Utah Jazz

Washington Wizards


4.2

$ cut -d ',' -f 3 nba2020.csv | tail -n+2  | sort | uniq | wc -l

30

4.3

$ cut -d ',' -f 2 nba2020.csv | tail -n+2 | sort | uniq

10:00p

10:30p

3:30p

5:00p

6:00p

7:00p

7:30p

8:00p

8:30p

9:00p

9:30p

4.4

$ cut -d ',' -f 2 nba2020.csv | tail -n+2 | sort | uniq | wc -l

12

**Important:** to skip the header of file you can use: 
    
`!tail -n+2 nba2020.csv`


Since,

``-n, --lines=[+]NUM       output the last NUM lines, instead of the last 10;
                             or use -n +NUM to output starting with line NUM``
        